### ISSUE TITLE
Separate resize step settings for vertical and horizontal?

### ISSUE THREAD

**Issue by jesseleite** [hsanson/vim-winmode#1]
What would you think of splitting up `g:win_mode_resize_step` into separate settings for vertical and horizontal?  Maybe something like:

```
let g:win_mode_horizontal_resize_step = 2
let g:win_mode_vertical_resize_step = 5
```

And both of these could fallback to `g:win_mode_resize_step` for backwards compatibility.   Thoughts?

**Comment by hsanson** [comment]
Should not be difficult to do and sounds like an useful feature.

**Comment by jesseleite** [comment]
Thanks for implementing!  Works great 🎉

**Comment by hsanson** [comment]
I find incredible that a few days ago was reading this blog https://jesseleite.com/posts/4/project-search-your-feelings and started integrating the workflow described there to [my own](https://github.com/hsanson/dotvim/commit/4e1a4be0aebdc41f1953d1cf0466098319a45223#diff-2b0aa7ee6675f69233c68ab94934cbe5R654).

So thanks to you too @jesseleite, I am glad I was able to give something back.

**Comment by jesseleite** [comment]
@hsanson Cool 🙌 Thank you for kind words, and for your contributions to vim world as well ❤️

Fzf's `:Ag` is nice indeed.  If you need more power (like searching .gitignore'd files, searching word under cursor, searching visual selection, etc.) check out my [vim-agriculture](https://github.com/jesseleite/vim-agriculture) extension, which maybe you know about as it's detailed in post as well.
